
server:
  port: 8080

spring:
  datasource:
    username: root
    password: ml123456
    url: jdbc:mysql://10.28.12.93:3306/arena?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.athlete.ranking

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
